# Sync repository labels
# Uses crazy-max/ghaction-github-labeler to apply

- name: type:feature
  color: 0e8a16
  description: New feature or enhancement

- name: type:bug
  color: ff3b30
  description: Something is not working

- name: type:docs
  color: 0b5fff
  description: Documentation updates

- name: type:chore
  color: 6a737d
  description: Maintenance tasks

- name: status:todo
  color: d4c5f9
  description: Planned, not started

- name: status:in-progress
  color: fbca04
  description: Work in progress

- name: status:blocked
  color: ff5967
  description: Blocked or needs input

- name: status:ready
  color: c2e0c6
  description: Ready for work/review

- name: priority:p0
  color: b60205
  description: Critical priority

- name: priority:p1
  color: d93f0b
  description: High priority

- name: priority:p2
  color: fbca04
  description: Medium priority

- name: area:auth
  color: 5319e7
  description: Authentication & authorization

- name: area:dashboard
  color: 0052cc
  description: Dashboards and UI modules

- name: area:infra
  color: 1d76db
  description: CI/CD, tooling, deployment

- name: area:compliance
  color: 0e8a16
  description: HIPAA, a11y, security

- name: good first issue
  color: 7057ff
  description: Good for newcomers
