name: Sync Labels

on:
  push:
    branches: [ main, cursor/** ]
    paths:
      - '.github/labels.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
          skip-delete: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}