name: Release Tagger
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create tag from last commit message
        id: tag
        run: |
          MSG=$(git log -1 --pretty=%s | tr ' ' '-')
          TAG="auto-$(date +%Y%m%d)-${MSG:0:32}"
          git tag -a "$TAG" -m "Automated release tag"
          git push origin "$TAG"
